// 200
const SUCCESS_CREATED_STATUS_CODE = 201;

// // 400
// const BAD_REQUEST_STATUS_CODE = 400;
// const UNAUTHORIZED_STATUS_CODE = 401;
// const FORBIDDEN_STATUS_CODE = 403;
// const NOT_FOUND_STATUS_CODE = 404;
// const CONFLICT_STATUS_CODE = 409;

// // 500
// const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  SUCCESS_CREATED_STATUS_CODE,
  // BAD_REQUEST_STATUS_CODE,
  // NOT_FOUND_STATUS_CODE,
  // INTERNAL_SERVER_ERROR_STATUS_CODE,
  // UNAUTHORIZED_STATUS_CODE,
  // CONFLICT_STATUS_CODE,
  // FORBIDDEN_STATUS_CODE,
};
