// 200
const SUCCESS_STATUS_CODE = 200;
const SUCCESS_CREATED_STATUS_CODE = 201;
const NO_CONTENT_STATUS_CODE = 204;

// 400
const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;

// 500
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  SUCCESS_STATUS_CODE,
  SUCCESS_CREATED_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  NO_CONTENT_STATUS_CODE,
};
